# Generated by Django 3.2.4 on 2021-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
