# Generated by Django 3.2.4 on 2021-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210807_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
