# Generated by Django 3.2.4 on 2021-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210807_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
