# Generated by Django 3.2.4 on 2021-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210807_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='totalamount',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='total_price',
            new_name='totalamount',
        ),
    ]
